version: 2
executorType: machine

jobs:
  build:
    environment:
      - CMAKE_PATH: "/home/circleci/cmake-3.13.2-Linux-x86_64/bin"
      - BOOST_MAJOR: "1"
      - BOOST_MINOR: "71"
      - BOOST_PATCH: "0"

    steps:
      - type: checkout

      - type: shell
        name: Install cmake
        command: |
          cd ~
          wget --quiet https://cmake.org/files/v3.13/cmake-3.13.2-Linux-x86_64.tar.gz
          tar -xf cmake-3.13.2-Linux-x86_64.tar.gz

      - type: shell
        name: Install other dependencies
        command: |
          sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install g++-5

      - type: shell
        name: Install Boost
        command: |
          cd ~
          boost=boost_${BOOST_MAJOR}_${BOOST_MINOR}_${BOOST_PATCH}
          wget https://dl.bintray.com/boostorg/release/${BOOST_MAJOR}.${BOOST_MINOR}.${BOOST_PATCH}/source/${boost}.tar.bz2
          tar xf ${boost}.tar.bz2
          cd ${boost}
          ./bootstrap.sh
          ./b2 -j3 -d+0 --link=static --with-system --with-test --with-coroutine

      - type: shell
        name: Build
        command: |
          git submodule sync --recursive
          git submodule update --recursive --init
          mkdir build
          cd build
          export CXX=g++-5
          export CC=gcc-5
          export PATH="$CMAKE_PATH:$PATH"
          cmake .. -DBOOST_ROOT=~/boost_${BOOST_MAJOR}_${BOOST_MINOR}_${BOOST_PATCH}
          make -j3

      - type: shell
        name: Test
        command: |
          ./build/test-util --log_level=test_suite
          ./build/test-comm --log_level=test_suite
